config/routes.rb
Rails.application.routes.draw do


  get "usuarios/enlazar_a_vacante" => 'usuarios#enlazar_a_vacante', :as => :enlazar_a_vacante

  #metodo en el controlador para enviar la evaluation_hiring_manager
  get 'usuarios/enviar_evaluation_hiring_manager'

  resources :evaluation_hiring_managers

  

  get "usuarios/ver_respuestas_user" => 'usuarios#ver_respuestas_user', :as => :ver_respuestas_user

  resources :answer_questions
  get 'game/siguinte_pregunta'
  get 'game/responder'
  get 'game/home' => 'game#home', :as => :gameHome
  get 'game/gameOver' => 'game#gameOver', :as => :gameOver

  resources :questions_first_filters


  get 'search/create'
  get 'search/search_students'
  get 'search/search_vacantes_Admin'
  get 'search/search_evaluaciones_Admin'
  get 'search/search_vacantes_aplicadas_Admin'

  resources :notifications, only: [:index,:update]
  get 'notifications/index'
  get "notifications/view_all_notifications" => 'notifications#view_all_notifications', :as => :view_all_notifications
  
  resources :evaluations
  resources :vacantes
  resources :usuarios, as: :users,only: [:show,:update ,:edit, :index]
  resources :administradores, as: :admins,only: [:show,:update ,:edit, :index]

  resources :vacante_aplicadas


  devise_for :admins,controllers: { registrations: 'admins/registrations' }

  devise_for :users

  get "main/adminRegister" => 'main#adminRegister', :as => :adminRegister
  get "main/adminLogin" => 'main#adminLogin', :as => :adminLogin

  authenticated :admin do
    root 'main#homeAdmin'
  end

  authenticated :user do
  	root 'main#home'
  end

  unauthenticated :user do
    root 'main#unregistered'
  end

  unauthenticated :admin do
    root 'main#adminLogin'
  end

   

  

  mount ActionCable.server => '/cable'
  #mount Sidekiq::Web => '/sidekiq'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vacante.rb
class Vacante < ApplicationRecord
  belongs_to :admin
  scope :nuevos, ->{order("created_at desc")}
  scope :no_occupied, -> {where(occupied:false)}
  
  #belongs_to :job_area, class_name: "TC::Job_area"
  validates :area, presence: true
  validates :planta, presence: true

  validates :mes_inicio, presence: true
  validates :mes_fin, presence: true

  validates :email_hiring_manager, presence: true

  has_many :vacantes_aplicadas
    
end

app/controllers/vacantes_controller.rb
class VacantesController < ApplicationController
  before_action :set_vacante, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new , :index ,:edit, :update, :destroy]

  # GET /vacantes
  # GET /vacantes.json
  def index
    #@vacantes = Vacante.all
    #@vacantess = current_admin.vacantes.nuevos.paginate(page:params[:page], per_page:20)
    @vacantess = Vacante.all.nuevos.paginate(page:params[:page], per_page:20)
  end

  # GET /vacantes/1
  # GET /vacantes/1.json
  def show
    @vacante_aplicada = VacanteAplicada.new
  end

  # GET /vacantes/new
  def new
    @vacante = Vacante.new
  end

  # GET /vacantes/1/edit
  def edit
  end

  # POST /vacantes
  # POST /vacantes.json
  def create
    @vacante = current_admin.vacantes.new(vacante_params)

    respond_to do |format|
      if @vacante.save
        format.html { redirect_to @vacante, notice: 'Vacante was successfully created.' }
        format.json { render :show, status: :created, location: @vacante }
      else
        format.html { render :new }
        format.json { render json: @vacante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vacantes/1
  # PATCH/PUT /vacantes/1.json
  def update
    respond_to do |format|
      if @vacante.update(vacante_params)
        format.html { redirect_to @vacante, notice: 'Vacante was successfully updated.' }
        format.json { render :show, status: :ok, location: @vacante }
      else
        format.html { render :edit }
        format.json { render json: @vacante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacantes/1
  # DELETE /vacantes/1.json
  def destroy

    @vacantess_aplicadas = VacanteAplicada.where(vacante_id: @vacante.id) #destrir todas las vacantes_aplicadas que sean de esta vacante
    if(@vacantess_aplicadas)
    
      @vacantess_aplicadas.each do |vacante_aplicada|
        @notifications = Notification.where(item_id: vacante_aplicada.id).unviewed  #notificaciones de cada vacante_aplicada
        if(@notifications)
          @notifications.destroy_all #destruye todas las notificaciones que tengan que ver con esta vacante_aplicada
        end
      end

      @vacantess_aplicadas.destroy_all #destruye todas las vacantes_aplicadas que tengan que ver con esta vacante
    end

    @vacante.destroy
    respond_to do |format|
      format.html { redirect_to vacantes_url, notice: 'Vacante was successfully destroyed.' }
      format.json { head :no_content }
    end


  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vacante
      @vacante = Vacante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vacante_params
      params.require(:vacante).permit(:name, :area, :location, :little_description, :description, :missions_role, :occupied ,:periodo_de_practica, :Name_Hiring_Manager, :planta,  :job_area_id , :mes_inicio, :mes_fin, :email_hiring_manager )
    end
end

app/helpers/vacantes_helper.rb
module VacantesHelper	

  def fechaBonita date
  	theDate = date.strftime("%b. %e, %Y")
  	theDate.html_safe
    
  end




end

app/views/vacantes/_form.html.haml
= form_for @vacante do |f|
  - if @vacante.errors.any?
    #error_explanation
      %h4.text-center= "#{pluralize(@vacante.errors.count, "error")} prohibited this vacante from being saved:"
      %ul.text-center
        - @vacante.errors.full_messages.each do |message|
          %li= message

  .row.center-xs
    .col-xs-9
      .box

        .row
          .col.s12
            .row.text-left
              .div.input-field.col.s6

                = f.text_field :name, autofocus: true, class:"" ,id:"name"
                = f.label :Nombre_vacante, class:"blue-text", for:"name"

              .div.input-field.col.s6
                =f.select :area, TC::Job_area.all.ordenados.collect { |u| [u.job_area, u.id] }, include_blank: "", placeholder:"Placeholder"
                %label.blue-text Area a la que pertenece la vacante




              .div.input-field.col.s6
                = f.text_field :location, class:"" , id:"location"
                = f.label :locación, class:"blue-text", for:"location"


              .div.input-field.col.s6
                =f.select :planta, TC::Plant.all.ordenados.collect { |u| [u.planta, u.id] }, include_blank: "", placeholder:"Placeholder"
                %label.blue-text Planta




              .div.input-field.col.s3 
                =f.select :mes_inicio, TC::Month.all.collect { |u| [u.mes, u.id] }, include_blank: "", placeholder:"Placeholder"
                %label.blue-text Mes de inicio

              .div.input-field.col.s3 
                =f.select :mes_fin, TC::Month.all.collect { |u| [u.mes, u.id] }, include_blank: "", placeholder:"Placeholder"
                %label.blue-text Mes fin

              .div.input-field.col.s3
                = f.text_field :Name_Hiring_Manager, class:"", id:"Name_Hiring_Manager"
                = f.label :Nombre_Hiring_Manager, class:"blue-text", for:"Name_Hiring_Manager"

              .div.input-field.col.s3 
                = f.email_field :email_hiring_manager, class:"", id:"email_hiring_manager"
                = f.label :email_hiring_manager, class:"blue-text", for:"email_hiring_manager"

              


              .div.input-field.full-width
                = f.text_area :description,id:"textarea1", class:"anchoLetra materialize-textarea"
                = f.label :description, class:"blue-text"

              .div.input-field.full-width
                = f.text_area :missions_role,id:"textarea1", class:"anchoLetra materialize-textarea"
                = f.label :missions_role, class:"blue-text"


              .div.input-field.col.s12
                = f.check_box :occupied, id:"occupied"
                = f.label :ocupado, for:"occupied"

              .div.input-field.col.s12


              .field.ocultar
                = f.label :admin
                = f.text_field :admin


            .actions.top-space2
              = f.submit 'Save', class:"btn full-width"

            %p *Checar que el correo del hiring manager sea correcto.

app/views/vacantes/_vacante.haml
%article.large-padding.white.top-space.full-width.z-depth-2
  /.line-block.text-right=post.area
  .text-left.relative.lighter
    =vacante.name
    .line-block.text-right
      =fechaBonita vacante.created_at

    .div
      =vacante.location

    .div
      =TC::Job_area.find(vacante.area).job_area

      

         
  %p.top-space.text-left.agregarMargenArriba.letraPost.bold-text=vacante.description[0..240] + "..."

  .actions.text-right
    = link_to "Ver" , vacante, class:"waves-effect waves-light btn"

app/views/vacantes/_vacanteLista.haml
%table
	- @vacantess.each do |vacante|
		%tr.border-bottom
			%td= vacante.name
			%td=TC::Job_area.find(vacante.area).job_area 
			%td= vacante.location
			%td= vacante.occupied
			%td= vacante.admin.name
			%td=fechaBonita vacante.created_at
			%td= link_to 'Show', vacante
			%td= link_to 'Edit', edit_vacante_path(vacante)
			%td= link_to 'Destroy', vacante, method: :delete, data: { confirm: 'Are you sure?' }

app/views/vacantes/edit.html.haml
%body.white-background

%h4.text-center Editando vacante

= render 'form'

= link_to 'Show', @vacante
\|
= link_to 'Back', vacantes_path

app/views/vacantes/index.html.haml
%body.white-background

%h4 Lista de vacantes

=render 'partials/buscadorVacantesAdmin'

= render "partials/preloader" 

%table
  %thead
    %tr
      %th Name
      %th Area
      %th Locación
      %th Ocupado
      %th Admin
      %th Fecha

      

  %tbody#data
    %div
      - @vacantess.each do |vacante|
        %tr.border-bottom
          %td= vacante.name
          %td=TC::Job_area.find(vacante.area).job_area 
          %td= vacante.location
          %td= vacante.occupied
          %td= vacante.admin.name
          %td=fechaBonita vacante.created_at
          %td= link_to 'Show', vacante
          %td= link_to 'Edit', edit_vacante_path(vacante)
          %td= link_to 'Destroy', vacante, method: :delete, data: { confirm: 'Are you sure?' }

#pagination.center
  = will_paginate @vacantess

%br

/= link_to 'Nueva Vacante', new_vacante_path

app/views/vacantes/new.html.haml
%body.white-background

%h4.text-center Crear vacante

= render 'form'

= link_to 'Back', vacantes_path

app/views/vacantes/show.html.haml
%body.white-background
/%p#notice= notice

.row.center-xs
  .col-xs-7
    .box.text-left
      %p
        %b Name:
        = @vacante.name
      %p
        %b Publication date:
        = fechaBonita @vacante.created_at
      %p
        %b Area:
        =TC::Job_area.find(@vacante.area).job_area
        /=@vacante.job_area.job_area 
      %p
        %b Location:
        = @vacante.location

      %p
        %b Descripción:
        = simple_format(@vacante.description)
      %p
        %b Missions role:
        = simple_format(@vacante.missions_role)
      %p
        %b Name Hiring Manager:
        = @vacante.Name_Hiring_Manager

      %p
        %b Correo Hiring Manager:
        = @vacante.email_hiring_manager

      %p
        %b Periodo practica:
        =TC::Month.find(@vacante.mes_inicio).mes
        a
        =TC::Month.find(@vacante.mes_fin).mes
      %p
        %b Planta:
        =TC::Plant.find(@vacante.planta).planta
      %p
        %b Occupied:
        = @vacante.occupied
      %p
        %b Admin:
        = @vacante.admin.name

      -if current_user
        = form_for @vacante_aplicada do |f|

          .ocultar        
            = f.text_field :user_id, value: current_user.id
          .ocultar
            = f.text_field :vacante_id, value: @vacante.id
    

          .actions
            = f.submit "Aplicar" ,class:"waves-effect waves-light btn full-width"





/= link_to 'Edit', edit_vacante_path(@vacante)
\|
= link_to 'Back', vacantes_path