config/routes.rb
Rails.application.routes.draw do


  get "usuarios/enlazar_a_vacante" => 'usuarios#enlazar_a_vacante', :as => :enlazar_a_vacante

  #metodo en el controlador para enviar la evaluation_hiring_manager
  get 'usuarios/enviar_evaluation_hiring_manager'

  resources :evaluation_hiring_managers

  

  get "usuarios/ver_respuestas_user" => 'usuarios#ver_respuestas_user', :as => :ver_respuestas_user

  resources :answer_questions
  get 'game/siguinte_pregunta'
  get 'game/responder'
  get 'game/home' => 'game#home', :as => :gameHome
  get 'game/gameOver' => 'game#gameOver', :as => :gameOver

  resources :questions_first_filters


  get 'search/create'
  get 'search/search_students'
  get 'search/search_vacantes_Admin'
  get 'search/search_evaluaciones_Admin'
  get 'search/search_vacantes_aplicadas_Admin'

  resources :notifications, only: [:index,:update]
  get 'notifications/index'
  get "notifications/view_all_notifications" => 'notifications#view_all_notifications', :as => :view_all_notifications
  
  resources :evaluations
  resources :vacantes
  resources :usuarios, as: :users,only: [:show,:update ,:edit, :index]
  resources :administradores, as: :admins,only: [:show,:update ,:edit, :index]

  resources :vacante_aplicadas


  devise_for :admins,controllers: { registrations: 'admins/registrations' }

  devise_for :users

  get "main/adminRegister" => 'main#adminRegister', :as => :adminRegister
  get "main/adminLogin" => 'main#adminLogin', :as => :adminLogin

  authenticated :admin do
    root 'main#homeAdmin'
  end

  authenticated :user do
  	root 'main#home'
  end

  unauthenticated :user do
    root 'main#unregistered'
  end

  unauthenticated :admin do
    root 'main#adminLogin'
  end

   

  

  mount ActionCable.server => '/cable'
  #mount Sidekiq::Web => '/sidekiq'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_buscadorEstudiantes.html.erb
<div class="row center-xs box z-depth-1">

	<div class="col-xs-12">

		<div class="">


			<div class="">
		     <%=form_tag "/search/search_students", method: :get,class:"" , remote: true, id:"search-form" do  %>

		      <div class="input-field col s4">
		      	<%= select_tag :keywordUniversidad, options_for_select(TC::University.all.ordenados.collect{ |u| [u.universidad, u.id] }) ,include_blank: true %>

		      	<label class="">Universidad</label>
		      </div>


		      <div class="input-field col s4">
		      	<%= select_tag :keywordCarrera, options_for_select(TC::Carrer.all.ordenados.collect{ |u| [u.carrera, u.id] }) ,include_blank: true %>

		      	<label class="">Carrera</label>
		      </div>


		       <div class="input-field col s4">
		      	<%= select_tag :keywordStatus, options_for_select(TC::Status.all.collect.collect{ |u| [u.status, u.id] }) ,include_blank: true %>

		      	<label class="">Status</label>
		      </div>


		      <div class="input-field col s4">
		      	<%=text_field_tag :keywordNombre, nil, placeholder: "Nombre", class:"labelBuscador" %>
		      </div>

		       <div class="input-field col s4">
		      	<%=text_field_tag :keywordApaterno, nil, placeholder: "Apellido paterno", class:"labelBuscador" %>
		      </div>

		      <div class="input-field col s4">
		      	<%=text_field_tag :keywordNAmaterno, nil, placeholder: "Apellido materno", class:"labelBuscador" %>
		      </div>



          	   	  <button class="buttonBuscador" type="submit">Buscar</button>

        	<% end %>
			</div>



		</div>

	</div>

</div>

app/views/partials/_buscadorEvaluacionesAdmin.html.erb
<div class="row left-xs">

	<div class="col-xs-10">

		<div class="box">


			<div class="">
		     <%=form_tag "/search/search_evaluaciones_Admin", method: :get, remote: true, id:"search-form" do  %>

		      <div class="input-field col s2">
		      	<%=text_field_tag :keywordUserName, nil, placeholder: "Por nombre ", class:"labelBuscador" %>
		      </div>

		      <div class="input-field col s2">
		      	<%=text_field_tag :keywordUser_1_lastname, nil, placeholder: "Apellido paterno ", class:"labelBuscador" %>
		      </div>

		      <div class="input-field col s2">
		      	<%=text_field_tag :keywordUser_2_lastname, nil, placeholder: "Apellido materno", class:"labelBuscador" %>
		      </div>


		      <div class="input-field col s2">
		      	<%= select_tag :keywordGlobalCandidate, options_for_select(TC::Rank_candidate.all.collect{ |u| [u.rank, u.id] }) ,include_blank: true %>

		      	<label class="">Rango</label>
		      </div>


		       <div class="input-field col s1">
		      	<%= select_tag :keywordCandidatoPotencial, options_for_select([["true","t"],["false","f"]]) ,include_blank: "" %>
		      	<label>Candidato potencial</label>

		      </div>


		      <div class="input-field col s1">
		      	<%= select_tag :keywordAssessment, options_for_select([["true","t"],["false","f"]]) ,include_blank: "" %>
		      	<label>Assessment</label>

		      </div>



		      <div class="input-field col s2">
		      	<button class="waves-effect waves-light btn buttonBuscador" type="submit">Search</button>

		      </div>


          	   	  

        	<% end %>
			</div>



		</div>

	</div>

</div>

app/views/partials/_buscadorVacantes.html.erb
<div class="row center-xs">

	<div class="col-xs-10">

		<div class="box z-depth-1">


			<div class="">
		     <%=form_tag "/search/create", method: :get, remote: true, id:"search-form" do  %>

		      <div class="input-field col s4">
		      	<%= select_tag :keywordArea, options_for_select(TC::Job_area.all.ordenados.collect{ |u| [u.job_area, u.id] }) ,include_blank: true %>

		      	<label class="">Area</label>
		      </div>



		      <div class="input-field col s4">
		      	<%=text_field_tag :keywordLocation, nil, placeholder: "Por locación", class:"labelBuscador" %>

		      </div>


		      <div class="input-field col s4">
		      	<%=text_field_tag :keywordName, nil, placeholder: "Por nombre", class:"labelBuscador" %>

		      </div>


          	   	  <button class="buttonBuscador" type="submit">Buscar</button>

        	<% end %>
			</div>



		</div>

	</div>

</div>

app/views/partials/_buscadorVacantesAdmin.html.erb
<div class="row center-xs">

	<div class="col-xs-12">

		<div class="box">


			<div class="">
		     <%=form_tag "/search/search_vacantes_Admin", method: :get, remote: true, id:"search-form" do  %>

		      <div class="input-field col s2">
		      	<%=text_field_tag :keywordName, nil, placeholder: "Por nombre vacante", class:"labelBuscador" %>

		      </div>


		      <div class="input-field col s2">
		      	<%= select_tag :keywordArea, options_for_select(TC::Job_area.all.collect.collect{ |u| [u.job_area, u.id] }) ,include_blank: true %>

		      	<label class="">Area</label>
		      </div>


		      <div class="input-field col s2">
		      	<%=text_field_tag :keywordLocation, nil, placeholder: "Por locación", class:"labelBuscador" %>

		      </div>

		       <div class="input-field col s2">
		      	<%= select_tag :keywordOccupied, options_for_select([["true","t"],["false","f"]]) ,include_blank: "" %>
		      	<label>ocupado</label>

		      </div>


		      <div class="input-field col s2">
		      	<%=text_field_tag :keywordAdmin, nil, placeholder: "Por Admin", class:"labelBuscador" %>
		      </div>



		      <div class="input-field col s2">
		      	<button class="waves-effect waves-light btn buttonBuscador" type="submit">Buscar</button>

		      </div>


          	   	  

        	<% end %>
			</div>



		</div>

	</div>

</div>

app/views/partials/_buscadorVacantesAplicadasAdmin.html.erb
<div class="row left-xs">

	<div class="col-xs-8">

		<div class="box">


			<div class="">
		     <%=form_tag "/search/search_vacantes_aplicadas_Admin", method: :get, remote: true, id:"search-form" do  %>

		      <div class="input-field col s2">
		      	<%=text_field_tag :keywordUserName, nil, placeholder: "Por nombre ", class:"labelBuscador" %>
		      </div>

		      <div class="input-field col s2">
		      	<%=text_field_tag :keywordUser_1_lastname, nil, placeholder: "apellido paterno", class:"labelBuscador" %>
		      </div>

		      <div class="input-field col s2">
		      	<%=text_field_tag :keywordUser_2_lastname, nil, placeholder: "apellido materno", class:"labelBuscador" %>
		      </div>


		      <div class="input-field col s4">
		      	<%=text_field_tag :keywordVacanteName, nil, placeholder: "Por nombre de la vacante", class:"labelBuscador" %>

		      </div>
		 

		      <div class="input-field col s2">
		      	<button class="waves-effect waves-light btn buttonBuscador" type="submit">Buscar</button>

		      </div>


          	   	  

        	<% end %>
			</div>



		</div>

	</div>

</div>

app/views/partials/_modalRespuestasUser.html.erb
  <div id="modalRespuestasPartial" class="modal">
    <div class="modal-content">
      <h4 class="blue-text">Respuestas</h4>


          <% @answer_questions.each do |answer| %>

          <div class="top-space">
          	<b class="line"><%= QuestionsFirstFilter.find(answer.questions_first_filter_id).pregunta   %> </b>


          	<% if answer.respuesta == true %>

          		<p class="line" > CORRECTO </p>

          	<% else %>
          		<p class="line" > INCORRECTO </p>

          	<% end %>
          	

          </div>
          	

          <% end %>

      <% if @answer_questions.blank? %>

        <p> No ha contestado la encuesta </p>

      <% end %>


    </div>
    <div class="modal-footer">
      <a  class="modal-action modal-close waves-effect waves-green btn-flat">De acuerdo</a>
    </div>
  </div>

app/views/partials/_nav.html.erb
<nav>
    <div class="nav-wrapper">

      <a class="brand-logo">Faurecia Students</a>

      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li>
        	<% if current_user.university and current_user.carrer %>
        		<%= link_to "Vacantes" , root_path, class:"white-text right-space"%>
        	<% end %>
        </li>
        <li> <%= link_to current_user.name , edit_user_path(current_user), class:"white-text right-space"%> </li>
        <li>  <%= link_to "Sign out" , destroy_user_session_path, method: :delete ,class:"white-text"%>   </li>
      </ul>
    </div>
 </nav>






  <!--  <%= link_to "Faurecia Students" ,root_path, class:"brand-logo", style: "text-decoration:none;"%> -->

app/views/partials/_navAdmin.html.erb
<nav>
    <div class="nav-wrapper">
       <%= link_to "Faurecia Admin" ,root_path, class:"brand-logo", style: "text-decoration:none;"%>
      <ul id="nav-mobile" class="right hide-on-med-and-down">


        <li><%= link_to "Vacantes aplicadas" , vacante_aplicadas_path ,class:"white-text right-space"%></li>
        <li><%= link_to "Evaluaciones" , evaluations_path ,class:"white-text right-space"%></li>
        <li><%= link_to "Vacantes" , vacantes_path ,class:"white-text right-space"%></li>

        <li><%= link_to "Nueva vacante" , new_vacante_path ,class:"white-text right-space"%></li>



        <li> 

          <%= link_to "/notifications" , class:"white-text waves-effect waves-block waves-light", id:"notificationButton",remote: true,data: {type: "script"} , for:"#modal_notifications" do%>

          <!--  <%=current_admin.unviewed_notifications_count  %>   -->

          <i class="material-icons iconoNotificaciones">notifications</i> 

          <small class="notification-badge" id="notification"><%=current_admin.unviewed_notifications_count  %></small>

          <% end %> 
        </li>



        <li><a class="dropdown-button" href="#!" data-activates="dropdown1"> <%= current_admin.name %>  <i class="material-icons right">arrow_drop_down</i></a></li>



      </ul>
    </div>
  </nav>




<!--  MENU ACTUALIZAR PERFIL ADMINISTRADOR -->

<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to "update profile" , edit_admin_path(current_admin), class:""%></li>
  <li class="divider"></li>
  <li><%= link_to "Sign out" , destroy_user_session_path, method: :delete ,class:""%></li>

</ul>






<!-- Modal de la notificaciones -->
<a id="modal_notifications" class=" modal-trigger ocultar" href="#modal1">Modal</a>

  <!-- Modal Structure -->
  <div id="modal1" class="modal bottom-sheet">

    <div class="modal-content">
      <h4>Notificaciones</h4>

      <%= render "partials/preloaderNotifications" %>
      <!-- aqui en el id=notifications se concatenan todas las notificaciones -->
      <ul class="collection" id="notifications">
      </ul>

   </div>
    
    <div class="modal-footer">
      <%= link_to "Ver mas " , notifications_path ,class:"waves-effect waves-green btn-flat underline" %>

      <%= link_to "marcar todas las notificaciones como vistas " , view_all_notifications_path ,class:"waves-effect waves-green btn-flat" %>
    </div>

  </div>

app/views/partials/_noticeToast.html.erb
<% if notice %>

<script type="text/javascript">
Materialize.toast('<%= notice %>', 5000)
</script>


<% end %>