config/routes.rb
Rails.application.routes.draw do


  get "usuarios/enlazar_a_vacante" => 'usuarios#enlazar_a_vacante', :as => :enlazar_a_vacante

  #metodo en el controlador para enviar la evaluation_hiring_manager
  get 'usuarios/enviar_evaluation_hiring_manager'

  resources :evaluation_hiring_managers

  

  get "usuarios/ver_respuestas_user" => 'usuarios#ver_respuestas_user', :as => :ver_respuestas_user

  resources :answer_questions
  get 'game/siguinte_pregunta'
  get 'game/responder'
  get 'game/home' => 'game#home', :as => :gameHome
  get 'game/gameOver' => 'game#gameOver', :as => :gameOver

  resources :questions_first_filters


  get 'search/create'
  get 'search/search_students'
  get 'search/search_vacantes_Admin'
  get 'search/search_evaluaciones_Admin'
  get 'search/search_vacantes_aplicadas_Admin'

  resources :notifications, only: [:index,:update]
  get 'notifications/index'
  get "notifications/view_all_notifications" => 'notifications#view_all_notifications', :as => :view_all_notifications
  
  resources :evaluations
  resources :vacantes
  resources :usuarios, as: :users,only: [:show,:update ,:edit, :index]
  resources :administradores, as: :admins,only: [:show,:update ,:edit, :index]

  resources :vacante_aplicadas


  devise_for :admins,controllers: { registrations: 'admins/registrations' }

  devise_for :users

  get "main/adminRegister" => 'main#adminRegister', :as => :adminRegister
  get "main/adminLogin" => 'main#adminLogin', :as => :adminLogin

  authenticated :admin do
    root 'main#homeAdmin'
  end

  authenticated :user do
  	root 'main#home'
  end

  unauthenticated :user do
    root 'main#unregistered'
  end

  unauthenticated :admin do
    root 'main#adminLogin'
  end

   

  

  mount ActionCable.server => '/cable'
  #mount Sidekiq::Web => '/sidekiq'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :admin
  belongs_to :item, polymorphic: true
  after_create {NotificationBroadcastJob.perform_later(self)}
  scope :unviewed, -> {where(viewed:false)}
  scope :latest, -> {order("created_at desc").limit(10)}


  def self.for_admin(admin_id)
  	Notification.where(admin_id: admin_id).unviewed.count

  end


  def check_date_users_notifacate
  	@vacantes_aplicadas = VacanteAplicada.where(status: 3)
  	@vacantes_aplicadas.each do |vacante_aplicada|
  		if(  (DateTime.now - vacante_aplicada.updated_at.to_datetime).to_i  == 120)

        #enviar evaluation a ahiring manager
        ManagerMailer.notify(vacante_aplicada.user, vacante_aplicada.vacante.email_hiring_manager , vacante_aplicada.vacante.admin).deliver 

        #notificacion al admin de que ya va a acabar
        Notification.create(item: vacante_aplicada, admin_id: item.cualAdmin)

  		end
  		
  	end
  	
  end
  
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
  	@notifications = Notification.where(admin:current_admin).unviewed.latest.paginate(page:params[:page], per_page:10)
  	respond_to do |format|
  		format.html
  		format.js
  	end
  end



  def update
  	@notification = Notification.find(params[:id])
  	message = if @notification.update(notification_params)
  		"Notificacion Vista"
  	else
  		"Hubo un error"
  	end
  	redirect_back , notice = message
  	
  end


  def view_all_notifications
  	@notifications = Notification.where(admin:current_admin).unviewed

  	@notifications.each do |notification|
  		Notification.update(notification.id, :viewed => true)
  	end

  	respond_to do |format|
  		format.html { redirect_to :back, notice: 'Todas las notificaciones vistas' }
  		format.js
  	end

  	
  end



  private
  def notification_params
  	params.require(:notification).permit(:viewed)
  		
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
	def render_notifications (notifications)
		notifications.map do |notification|
			render partial: "notifications/#{notification.item_type.downcase}", locals:{notification: notification}
		end.join("").html_safe
		
	end
end

app/views/notifications/_evaluationhiringmanager.html.erb
<li class="collection-item avatar">

      <i class="material-icons circle pink">content_paste</i>

      <span class="title"><%= link_to "El hiring manager ha completado la evaluación de #{notification.item.user.name} #{notification.item.user.firs_last_name} #{notification.item.user.second_last_name}" , notification.item , class:"black-text"  %></span>


      <% if notification.item.user.university %>
      	<p>Escuela: <%= TC::University.find(notification.item.user.university).universidad %> </p>

      <% else %>
      	<p>Escuela: No found </p>

      <% end %>



      <% if notification.item.user.carrer %>
      	<p>Carrera: <%= TC::Carrer.find(notification.item.user.carrer).carrera %> </p>

      <% else %>
      	<p>Carrera: No found </p>

      <% end %>  

      <%= link_to notification_path(id: notification.id,notification:{viewed: true}),method: :put, class:"secondary-content" do %>
            <i class="material-icons">check</i>

      <% end %>


</li>

app/views/notifications/_vacanteaplicada.html.erb
<% if notification.item.status == 1 %>



<li class="collection-item avatar">

      <i class="material-icons circle green">person</i>

      <span class="title"><%= link_to "#{notification.item.user.name} #{notification.item.user.firs_last_name} #{notification.item.user.second_last_name} aplico a la vacante #{notification.item.vacante.name}" , notification.item.user , class:"black-text"  %></span>


      <% if notification.item.user.university %>
      	<p>Escuela: <%= TC::University.find(notification.item.user.university).universidad %> </p>

      <% else %>
      	<p>Escuela: No found </p>

      <% end %>



      <% if notification.item.user.carrer %>
      	<p>Carrera: <%= TC::Carrer.find(notification.item.user.carrer).carrera %> </p>

      <% else %>
      	<p>Carrera: No found </p>

      <% end %>  

      <%= link_to notification_path(id: notification.id,notification:{viewed: true}),method: :put, class:"secondary-content" do %>
            <i class="material-icons">check</i>

      <% end %>


</li>


<% end %>








<% if notification.item.status == 3 %>



<li class="collection-item avatar">

      <i class="material-icons circle blue">today</i>

      <span class="title"><%= link_to "#{notification.item.user.name} #{notification.item.user.firs_last_name} #{notification.item.user.second_last_name} han pasado 4 meses desde su inicio, esta apunto de terminar sus practicas!!!!!" , notification.item.user , class:"black-text"  %></span>


      <% if notification.item.user.university %>
            <p>Escuela: <%= TC::University.find(notification.item.user.university).universidad %> </p>

      <% else %>
            <p>Escuela: No found </p>

      <% end %>



      <% if notification.item.user.carrer %>
            <p>Carrera: <%= TC::Carrer.find(notification.item.user.carrer).carrera %> </p>

      <% else %>
            <p>Carrera: No found </p>

      <% end %>  

      <%= link_to notification_path(id: notification.id,notification:{viewed: true}),method: :put, class:"secondary-content" do %>
            <i class="material-icons">check</i>

      <% end %>


</li>


<% end %>

app/views/notifications/evaluationhiringmanager.html.erb
<li class="collection-item avatar">

      <i class="material-icons circle green">person</i>

      <span class="title"><%= link_to "Han completado la evaluacion_hiring_manager de #{notification.item.user.name} #{notification.item.user.firs_last_name} #{notification.item.user.second_last_name}" , notification.item.user , class:"black-text"  %></span>


      <% if notification.item.user.university %>
      	<p>Escuela: <%= TC::University.find(notification.item.user.university).universidad %> </p>

      <% else %>
      	<p>Escuela: No found </p>

      <% end %>



      <% if notification.item.user.carrer %>
      	<p>Carrera: <%= TC::Carrer.find(notification.item.user.carrer).carrera %> </p>

      <% else %>
      	<p>Carrera: No found </p>

      <% end %>  

      <%= link_to notification_path(id: notification.id,notification:{viewed: true}),method: :put, class:"secondary-content" do %>
            <i class="material-icons">check</i>

      <% end %>


</li>

app/views/notifications/index.html.haml
%body.white-background

%h4.text-center Notificaciones

= link_to "marcar todas las notificaciones como vistas", view_all_notifications_path ,class:"underline" 

%ul.collection#notifications
	=render_notifications @notifications

%div#pagination.text-center
	= will_paginate @notifications