config/routes.rb
Rails.application.routes.draw do


  get "usuarios/enlazar_a_vacante" => 'usuarios#enlazar_a_vacante', :as => :enlazar_a_vacante

  #metodo en el controlador para enviar la evaluation_hiring_manager
  get 'usuarios/enviar_evaluation_hiring_manager'

  resources :evaluation_hiring_managers

  

  get "usuarios/ver_respuestas_user" => 'usuarios#ver_respuestas_user', :as => :ver_respuestas_user

  resources :answer_questions
  get 'game/siguinte_pregunta'
  get 'game/responder'
  get 'game/home' => 'game#home', :as => :gameHome
  get 'game/gameOver' => 'game#gameOver', :as => :gameOver

  resources :questions_first_filters


  get 'search/create'
  get 'search/search_students'
  get 'search/search_vacantes_Admin'
  get 'search/search_evaluaciones_Admin'
  get 'search/search_vacantes_aplicadas_Admin'

  resources :notifications, only: [:index,:update]
  get 'notifications/index'
  get "notifications/view_all_notifications" => 'notifications#view_all_notifications', :as => :view_all_notifications
  
  resources :evaluations
  resources :vacantes
  resources :usuarios, as: :users,only: [:show,:update ,:edit, :index]
  resources :administradores, as: :admins,only: [:show,:update ,:edit, :index]

  resources :vacante_aplicadas


  devise_for :admins,controllers: { registrations: 'admins/registrations' }

  devise_for :users

  get "main/adminRegister" => 'main#adminRegister', :as => :adminRegister
  get "main/adminLogin" => 'main#adminLogin', :as => :adminLogin

  authenticated :admin do
    root 'main#homeAdmin'
  end

  authenticated :user do
  	root 'main#home'
  end

  unauthenticated :user do
    root 'main#unregistered'
  end

  unauthenticated :admin do
    root 'main#adminLogin'
  end

   

  

  mount ActionCable.server => '/cable'
  #mount Sidekiq::Web => '/sidekiq'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer_question.rb
class AnswerQuestion < ApplicationRecord

  scope :nuevos, ->{order("created_at desc")}

  belongs_to :user
  belongs_to :questions_first_filter

  #evita que haya duplicados. deden ser unicos tanto el user_id como el questions_first_filter_id
  #es decir, no puede haber otro 1,2  u otro 3,5 , etc
  validates_uniqueness_of :user_id, :scope => :questions_first_filter_id


end

app/controllers/answer_questions_controller.rb
class AnswerQuestionsController < ApplicationController
  before_action :set_answer_question, only: [:show, :edit, :update, :destroy]

  # GET /answer_questions
  # GET /answer_questions.json
  def index
    @answer_questions = AnswerQuestion.all.nuevos
  end

  # GET /answer_questions/1
  # GET /answer_questions/1.json
  def show
  end

  # GET /answer_questions/new
  def new
    @answer_question = AnswerQuestion.new
  end

  # GET /answer_questions/1/edit
  def edit
  end

  # POST /answer_questions
  # POST /answer_questions.json
  def create
    @answer_question = AnswerQuestion.new(answer_question_params)

    respond_to do |format|
      if @answer_question.save
        format.html { redirect_to @answer_question, notice: 'Answer question was successfully created.' }
        format.json { render :show, status: :created, location: @answer_question }
      else
        format.html { render :new }
        format.json { render json: @answer_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answer_questions/1
  # PATCH/PUT /answer_questions/1.json
  def update
    respond_to do |format|
      if @answer_question.update(answer_question_params)
        format.html { redirect_to @answer_question, notice: 'Answer question was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer_question }
      else
        format.html { render :edit }
        format.json { render json: @answer_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answer_questions/1
  # DELETE /answer_questions/1.json
  def destroy
    @answer_question.destroy
    respond_to do |format|
      format.html { redirect_to answer_questions_url, notice: 'Answer question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer_question
      @answer_question = AnswerQuestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_question_params
      params.require(:answer_question).permit(:respuesta, :user_id , :questions_first_filter_id)
    end
end

app/helpers/answer_questions_helper.rb
module AnswerQuestionsHelper
end

app/views/answer_questions/_form.html.haml
= form_for @answer_question do |f|
  - if @answer_question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@answer_question.errors.count, "error")} prohibited this answer_question from being saved:"
      %ul
        - @answer_question.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :respuesta
    = f.check_box :respuesta
  .field
    = f.label :user
    = f.text_field :user
  .actions
    = f.submit 'Save'

app/views/answer_questions/edit.html.haml
%h1 Editing answer_question

= render 'form'

= link_to 'Show', @answer_question
\|
= link_to 'Back', answer_questions_path

app/views/answer_questions/index.html.haml
%h1 Listing answer_questions

%table
  %thead
    %tr
      %th Pregunta
      %th User
      %th Respuesta
      
      %th
      %th
      %th

  %tbody
    - @answer_questions.each do |answer_question|
      %tr

        %td=answer_question.questions_first_filter.pregunta

        %td
          = answer_question.user.name
          =answer_question.user.firs_last_name
          =answer_question.user.second_last_name

        %td
          -if answer_question.respuesta == true
            Correcta
          -else
            Incorrecta


        
        %td= link_to 'Show', answer_question
        %td= link_to 'Edit', edit_answer_question_path(answer_question)
        %td= link_to 'Destroy', answer_question, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Answer question', new_answer_question_path

app/views/answer_questions/new.html.haml
%h1 New answer_question

= render 'form'

= link_to 'Back', answer_questions_path

app/views/answer_questions/show.html.haml
%p#notice= notice

%p
  %b Respuesta:
  = @answer_question.respuesta
%p
  %b User:
  = @answer_question.user

= link_to 'Edit', edit_answer_question_path(@answer_question)
\|
= link_to 'Back', answer_questions_path